### ISSUE TITLE
Do you think you could shrink it a little to fit 1515 extrusions of a Micron+?

### ISSUE THREAD

**Issue by TekuSP** [juliusjj25/z-umbilical_mod#1]

**Comment by juliusjj25** [comment]
@TekuSP I am not familiar with the Micron geometry, but this mod uses one of the holes on the A/B drive of the V2.4. I uploaded the CAD if you'd like to make the mod yourself, but without knowing how this would interface with the Micron gantry, I can't easily make the change. 
![image](https://github.com/juliusjj25/z-umbilical_mod/assets/118471600/069912c8-f764-4d2e-a482-bd34efb6e684)
